/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-conventions")
}

dependencies {
    api(libs.org.springframework.cloud.spring.cloud.starter.oauth2)
    api(libs.org.springframework.boot.spring.boot.starter.security)
    api(libs.org.springframework.cloud.spring.cloud.starter.config)
    api(libs.org.springframework.boot.spring.boot.starter.web)
    api(libs.org.springframework.cloud.spring.cloud.starter.openfeign)
    api(libs.org.springframework.cloud.spring.cloud.starter.netflix.eureka.client)
    api(libs.org.springframework.cloud.spring.cloud.starter.sleuth)
    api(libs.org.springframework.boot.spring.boot.starter.data.mongodb)
    api(libs.org.springframework.boot.spring.boot.starter.actuator)
    api(libs.org.springframework.cloud.spring.cloud.starter.bus.amqp)
    api(libs.org.springframework.cloud.spring.cloud.netflix.hystrix.stream)
    api(libs.org.springframework.boot.spring.boot.starter.mail)
    testImplementation(libs.de.flapdoodle.embed.de.flapdoodle.embed.mongo)
    testImplementation(libs.com.jayway.jsonpath.json.path)
    testImplementation(libs.org.springframework.boot.spring.boot.starter.test)
}

description = "notification-service"
