/*
 * This file was generated by the Gradle 'init' task.
 */

rootProject.name = "piggymetrics"
include(":notification-service")
include(":auth-service")
include(":statistics-service")
include(":registry")
include(":account-service")
include(":monitoring")
include(":config")
include(":gateway")
include(":turbine-stream-service")
