/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-conventions")
}

dependencies {
    api(libs.org.springframework.cloud.spring.cloud.starter.netflix.zuul)
    api(libs.org.springframework.cloud.spring.cloud.starter.config)
    api(libs.org.springframework.cloud.spring.cloud.starter)
    api(libs.org.springframework.cloud.spring.cloud.starter.netflix.eureka.client)
    api(libs.org.springframework.cloud.spring.cloud.starter.sleuth)
    testImplementation(libs.org.springframework.boot.spring.boot.starter.test)
}

description = "gateway"
