/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("java")
    id("jacoco")
    id("buildlogic.java-conventions")
}

dependencies {
    api(libs.org.springframework.cloud.spring.cloud.starter.config)
    api(libs.org.springframework.cloud.spring.cloud.starter.netflix.hystrix.dashboard)
    testImplementation(libs.org.springframework.boot.spring.boot.starter.test)
}

description = "monitoring"
tasks.test {
    finalizedBy(tasks.jacocoTestReport)
}

tasks.jacocoTestReport {
    dependsOn(tasks.test)
    reports {
        xml.required.set(true)
        html.required.set(true)
    }
}