/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("java")
    id("jacoco")
    id("buildlogic.java-conventions")
}

dependencies {
    api(libs.org.springframework.boot.spring.boot.starter.data.mongodb)
    api(libs.org.springframework.cloud.spring.cloud.starter.config)
    api(libs.org.springframework.boot.spring.boot.starter.security)
    api(libs.org.springframework.cloud.spring.cloud.starter.oauth2)
    api(libs.org.springframework.boot.spring.boot.starter.web)
    api(libs.org.springframework.cloud.spring.cloud.starter.netflix.eureka.client)
    api(libs.org.springframework.cloud.spring.cloud.starter.sleuth)
    testImplementation(libs.org.springframework.boot.spring.boot.starter.test)
    testImplementation(libs.de.flapdoodle.embed.de.flapdoodle.embed.mongo)
    testImplementation(libs.com.jayway.jsonpath.json.path)
}

description = "auth-service"
tasks.test {
    finalizedBy(tasks.jacocoTestReport)
}

tasks.jacocoTestReport {
    dependsOn(tasks.test)
    reports {
        xml.required.set(true)
        html.required.set(true)
    }
}