/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-conventions")
}

dependencies {
    api(libs.org.springframework.cloud.spring.cloud.config.server)
    api(libs.org.springframework.boot.spring.boot.starter.security)
}

description = "config"
