/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    `java-library`
    `maven-publish`
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://open.reply.it/nexus/content/repositories/open-reply")
    }

    maven {
        url = uri("https://open.reply.it/nexus/content/repositories/open-reply-snapshots/")
    }

    maven {
        url = uri("https://open.reply.it/nexus/content/repositories/open-reply-bcc-snapshot")
    }

    maven {
        url = uri("https://open.reply.it/nexus/content/repositories/open-reply-bcc-release")
    }

    maven {
        url = uri("https://open.reply.it/nexus/content/repositories/thirdparty-ebr/")
    }

    maven {
        url = uri("https://open.reply.it/nexus/content/repositories/thirdparty/")
    }

    maven {
        url = uri("https://open.reply.it/nexus/content/repositories/public/")
    }

    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

group = "com.piggymetrics"
version = "1.0-SNAPSHOT"
java.sourceCompatibility = JavaVersion.VERSION_1_8

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}

tasks.withType<Javadoc>() {
    options.encoding = "UTF-8"
}
