/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-conventions")
}

dependencies {
    api(libs.org.springframework.cloud.spring.cloud.starter.config)
    api(libs.org.springframework.cloud.spring.cloud.starter.netflix.eureka.client)
    api(libs.org.springframework.cloud.spring.cloud.starter.netflix.turbine.stream)
    api(libs.org.springframework.cloud.spring.cloud.starter.stream.rabbit)
    testImplementation(libs.org.springframework.boot.spring.boot.starter.test)
}

description = "turbine-stream-service"
