name: Java CI with Gradle
on:
  workflow_dispatch:
    inputs:
      branch_to_clone:
        description: 'The branch of the private repo to clone'
        required: true
        default: 'develop/restructure' #change to main once ready
        type: string
      generate_test:
        description: 'Esegui generazione test automatica'
        required: false
        type: boolean
        default: false


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 8
      uses: actions/setup-java@v4
      with:
        java-version: '8'
        distribution: 'zulu'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v5
    
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Run aggregated tests with coverage (Jacoco)
      run: ./gradlew jacocoRootReport

    - name: Upload aggregated Jacoco coverage report
      uses: actions/upload-artifact@v4
      with:
        name: jacoco-root-report
        path: build/reports/jacoco/jacocoRootReport

  post-build:
    if: ${{ github.event.inputs.generate_test == 'true' }}
    needs: build
    uses: ./.github/workflows/post-build.yml
    with:
      branch_to_clone: ${{ github.event.inputs.branch_to_clone }}
      run_id: ${{ github.run_id }}
    secrets:
      POC_AI_READ_PAT: ${{ secrets.POC_AI_READ_PAT }}