name: Java CI with Gradle

on:
  workflow_dispatch:
    inputs:
      test:
        description: 'Test'
        required: true
        default: 'something'
        type: string


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 8
      uses: actions/setup-java@v4
      with:
        java-version: '8'
        distribution: 'zulu'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v5
    
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    # - name: Build with Gradle Wrapper
    #   run: ./gradlew build

    # - name: Run aggregated tests with coverage (Jacoco)
    #   run: ./gradlew jacocoRootReport

    # - name: Upload aggregated Jacoco coverage report
    #   uses: actions/upload-artifact@v4
    #   with:
    #     name: jacoco-root-report
    #     path: build/reports/jacoco/jacocoRootReport/html
    
    # Checkout external repo with Python scripts
    # - name: Add SSH key and clone private repo
    #   uses: webfactory/ssh-agent@v0.9.1
    #   with:
    #     ssh-private-key: ${{ secrets.POC_AI_READ_PRIVATE_KEY }}

    # - name: Clone private repo
    #   run: |
    #     git clone git@github.com:lcanevarolo/open-poc-ai-unit-tests.git ai-unit-tests
    #     ls -la ai-unit-tests
    - name: Clone private repo
      uses: actions/checkout@v4
      with:
        repository: lcanevarolo/open-poc-ai-unit-tests
        token: ${{ secrets.POC_AI_READ_PAT }}
        path: open-poc-ai-unit-tests


    # Set up Python
    - name: Set up Python 3.x
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    # Install requirements if requirements.txt exists
    - name: Install Python dependencies
      run: |
        pip install -r open-poc-ai-unit-tests/requirements.txt

    - name: Run command
      run: |
        la -a open-poc-ai-unit-tests
    # Run Python scripts (customize script names as needed)
    # - name: Run Python scripts
    #   run: |
    #     python open-poc-ai-unit-tests/main_script.py



