name: Generate Tests
on:
  workflow_dispatch:
    inputs:
      branch_to_clone:
        description: 'The branch of the private repo to clone'
        required: true
        default: 'demo_ale'
        type: string
      run_id:
        description: 'The run_id of the build workflow to fetch artifacts from'
        required: false
        type: string
        default: '22545934112'
  workflow_call:
    inputs:
      branch_to_clone:
        description: 'The branch of the private repo to clone'
        required: true
        type: string
      run_id:
        description: 'The run_id of the build workflow to fetch artifacts from'
        required: false
        type: string
    secrets:
      POC_AI_READ_PAT:
        required: true

jobs:
  post-build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'zulu'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5

      - uses: actions/checkout@v4
      - name: Download Jacoco XML report
        uses: actions/download-artifact@v4
        with:
          name: jacoco-root-report
          path: build/reports/jacoco/jacocoRootReport
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: ${{inputs.run_id }}
      - name: Rename Jacoco report file
        run: |
          mv build/reports/jacoco/jacocoRootReport/jacocoRootReport.xml build/reports/jacoco/jacocoTestReport.xml
      - name: Setup xmllint
        uses: Bpolitycki/setup-xmllint-action@1.0.1

      # - name: Extract Jacoco coverage (before)
      #   id: jacoco_coverage_before
      #   run: |
      #     COVERED=$(xmllint --xpath "string(//report/counter[@type='INSTRUCTION']/@covered)" build/reports/jacoco/jacocoRootReport/jacocoRootReport.xml)
      #     MISSED=$(xmllint --xpath "string(//report/counter[@type='INSTRUCTION']/@missed)" build/reports/jacoco/jacocoRootReport/jacocoRootReport.xml)
      #     TOTAL=$((COVERED + MISSED))
      #     if [ "$TOTAL" -eq 0 ]; then
      #       PERCENT=0
      #     else
      #       PERCENT=$((100 * COVERED / TOTAL))
      #     fi
      #     echo "COVERAGE_PERCENT_BEFORE=$PERCENT" >> $GITHUB_ENV

      - name: Clone private repo
        uses: actions/checkout@v5
        with:
          repository: lcanevarolo/open-poc-ai-unit-tests
          ref: ${{ inputs.branch_to_clone || github.event.workflow_run.head_branch }}
          token: ${{ secrets.POC_AI_READ_PAT }}
          path: open-poc-ai-unit-tests

      - name: Check application config file
        run: |
          ls -la open-poc-ai-unit-tests/
          ls -la open-poc-ai-unit-tests/resources/
          ls -la open-poc-ai-unit-tests/resources/config/
          cat open-poc-ai-unit-tests/resources/config/application.yaml

      - name: Update application.yaml
        uses: fjogeleit/yaml-update-action@main
        with:
          valueFile: 'open-poc-ai-unit-tests/resources/config/application.yaml'
          commitChange: false
          changes: |
            {
              "target_project_path": "${{ github.workspace }}",
              "executor.jvm_path": "${{ env.JAVA_HOME }}",
              "executor.baseline_run_needed": false
            }

      - name: Check application config file
        run: |
          cat open-poc-ai-unit-tests/resources/config/application.yaml

      - name: Set up Python 3.x
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Python dependencies
        run: |
          pip install -e ./open-poc-ai-unit-tests
      
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run Python scripts
        run: |
          export PYTHONPATH="${PYTHONPATH}:$(pwd)/open-poc-ai-unit-tests/src"
          cd open-poc-ai-unit-tests/src/cli
          pwd
          python ./cli.py

      - name: Check application config file
        run: |
          ls -la .poc_ai_output
          cat .poc_ai_output/manifest.json
      # - name: Re-run Jacoco coverage after Python script
      #   run: |
      #     cd ${{ github.workspace }}
      #     ./gradlew jacocoRootReport
     
      # - name: Extract Jacoco coverage (after)
      #   id: jacoco_coverage_after
      #   run: |
      #     COVERED=$(xmllint --xpath "string(//report/counter[@type='INSTRUCTION']/@covered)" build/reports/jacoco/jacocoRootReport/jacocoRootReport.xml)
      #     MISSED=$(xmllint --xpath "string(//report/counter[@type='INSTRUCTION']/@missed)" build/reports/jacoco/jacocoRootReport/jacocoRootReport.xml)
      #     TOTAL=$((COVERED + MISSED))
      #     if [ "$TOTAL" -eq 0 ]; then
      #       PERCENT=0
      #     else
      #       PERCENT=$((100 * COVERED / TOTAL))
      #     fi
      #     echo "COVERAGE_PERCENT_AFTER=$PERCENT" >> $GITHUB_ENV    
      # - name: Commit and push if coverage increased
      #  if: ${{ env.COVERAGE_PERCENT_AFTER > env.COVERAGE_PERCENT_BEFORE }}
      #   run: |
      #     git config --global user.name "github-actions"
      #     git config --global user.email "github-actions@github.com"
      #     BRANCH_NAME="auto/test-gen-increase-$(date +%Y%m%d%H%M%S)"
      #     git checkout -b "$BRANCH_NAME"
      #     git add .
      #     git commit -m "test(gen): auto-commit for increased coverage"
      #     git push --set-upstream origin "$BRANCH_NAME"
      #     #TODO: automate PR creation